name: Build

on:
  push:
    branches:
      - '*'
    tags:
      - '*'

env:
  PROJECT_NAME: OldBtd6Helper
  
  MOD_HELPER_NAME: Btd6ModHelper
  BLOONSTD6: BloonsTD6

jobs:
  build:
    
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: [ 39, 40, 41, 42, 43, 44, 45 ]

    steps:
      - name: Clone Repo
        uses: actions/checkout@master
        with:
          path: ${{ env.PROJECT_NAME }}


      - name: Download Latest MelonLoader
        if: env.MELONLOADER_BRANCH == ''
        uses: robinraju/release-downloader@v1.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: LavaGang/MelonLoader
          fileName: MelonLoader.x64.zip
          tarBall: false
          zipBall: false
          latest: true
      - name: Extract Latest MelonLoader
        if: env.MELONLOADER_BRANCH == ''
        shell: bash
        run: unzip MelonLoader.x64.zip -d ${{ env.BLOONSTD6 }}


      - name: Download Specific MelonLoader
        if: env.MELONLOADER_BRANCH != ''
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: build.yml
          branch: ${{ env.MELONLOADER_BRANCH }}
          name: MelonLoader.Linux.x64.CI.Release
          repo: LavaGang/MelonLoader
          path: ${{ env.BLOONSTD6 }}


      - name: Clone Dependencies Repo
        uses: actions/checkout@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: doombubbles/btd6-ci-dependencies
          ref: v${{ matrix.version }}
          path: ${{ env.BLOONSTD6 }}/MelonLoader/Il2CppAssemblies


      - name: Download Latest Mod Helper
        uses: robinraju/release-downloader@v1.4
        if: env.MOD_HELPER_BRANCH == ''
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: gurrenm3/BTD-Mod-Helper
          fileName: ${{ env.MOD_HELPER_NAME }}.dll
          out-file-path: ${{ env.BLOONSTD6 }}/Mods/
          tarBall: false
          zipBall: false
          latest: true


      - name: Download Specific Mod Helper
        uses: dawidd6/action-download-artifact@v2
        if: env.MOD_HELPER_BRANCH != ''
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: build.yml
          name: ${{ env.MOD_HELPER_NAME }}.dll
          branch: ${{ env.MOD_HELPER_BRANCH }}
          repo: gurrenm3/BTD-Mod-Helper
          path: ${{ env.BLOONSTD6 }}/Mods/


      - name: Download btd6.targets
        shell: bash
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            choco install -y wget
          fi
          wget https://raw.githubusercontent.com/gurrenm3/BTD-Mod-Helper/master/BloonsTD6%20Mod%20Helper/btd6.targets
          ls -r


      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x


      - name: Build
        run: dotnet build -c "v${{ matrix.version }}" -p:BloonsTD6="../${{ env.BLOONSTD6 }}" "${{ env.PROJECT_NAME }}/${{ env.PROJECT_NAME }}.csproj"


      - name: Upload Mod DLL
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PROJECT_NAME }}${{ matrix.version }}.dll
          path: ${{ env.BLOONSTD6 }}/Mods/${{ env.PROJECT_NAME }}${{ matrix.version }}.dll
          if-no-files-found: error
  
  deploy:
    runs-on: ubuntu-latest
    needs: [ build ]
    
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
      - name: Clone Repo
        uses: actions/checkout@master
        with:
          path: ${{ env.PROJECT_NAME }}
          
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: Mods
          pattern: ${{ env.PROJECT_NAME }}*.dll
          merge-multiple: true

      - name: List files
        id: list_files
        run: |
          echo 'FILES<<EOF' >> $GITHUB_OUTPUT
          find "Mods" -name "*.dll" >> $GITHUB_OUTPUT
          echo EOF >> $GITHUB_OUTPUT

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ steps.list_files.outputs.FILES }}
          body_path: ${{ env.PROJECT_NAME }}/LATEST.md